# btop Configuration
# Catppuccin Macchiato

color_theme = Default
theme_background = False
truecolor = True
force_tty = False
preserve_aspect_ratio = True

update_ms = 2000
proc_sorting = cpu lazy
proc_reversed = False
proc_per_core = True

temp_scale = celsius
base_10_sizes = False
show_coretemp = True

rounded_corners = True
graph_symbol = block
graph_lines = True

proc_gradient = True
cpu_graph_upper = #8aadf4
cpu_graph_lower = #363a4f
mem_graph_upper = #a6da95
mem_graph_lower = #363a4f
swap_graph_upper = #eed49f
swap_graph_lower = #363a4f
net_graph_upper = #c6a0f6
net_graph_lower = #363a4f
proc_color = #8aadf4
