splash = false

wallpaper {
    monitor = HDMI-A-2
    path = /home/nils/pictures/wallpaper/anime-girl-with-katana.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-4
    path = /home/nils/pictures/wallpaper/anime-girl-with-katana.jpg
    fit_mode = cover
}
